"""Song table

Revision ID: 98d90aa5a75b
Revises: 
Create Date: 2020-07-03 14:05:15.332910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98d90aa5a75b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('song',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('meter_name', sa.String(), nullable=True),
    sa.Column('song_text', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('three_liner', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('song')
    # ### end Alembic commands ###
